### ISSUE TITLE
Rika Paro

### ISSUE THREAD

**Issue by boxsters1423** [openhautomation/rikaha#23]
Hello,
Avec le Rika Paro je reçois des états : "Etat inconnu" de la part du plugin. 
Peut-être il s'agit de status spécifiques au mode mixte comme le "Contrôle bois" qui vérifie si le poêle est en mode pellet ou en mode bois. Si je peux aider merci de me dire comment.
Salutations et merci pour ce plugin.

**Comment by openhautomation** [comment]
Bonsoir, merci pour ton retour.

tu peux m'aider en me donnant l'état que tu vois s'afficher et les valeurs des commandes, 'statusMainState'et 'statusSubState'. Merci

**Comment by boxsters1423** [comment]
Avec plaisir.
Par contre je ne connais pas encore très bien l’administration du Jeedom. Logs et historique.
Comment je peux ajouter des logs pour voir plus que les 5 dernières minutes ?
Si je vais dans l’historique pour le statut je n’ai rien malgré que j’ai tout historisé.

Au plaisir de t’aider c’est un super boulot !!

**Comment by boxsters1423** [comment]
Salut,

Malheureusement comme j’étais pas devant mon poêle Paro je ne sais pas ce qui était affiché à l’écran. Faudrait que j’installe une webcam  😀
Mais voici les valeurs des différentes variables que tu m’as demandé plus le warning et erreur.



Et il n’y a pas de widget pour le Paro si je met Standard et que je reviens dans l’écran ça disparaît. Si je peux t’aider de quelque manière que ce soit n’hésites pas et j’essaierai. Je suis pas encore spécialiste des widget et tout ce qui est présentation.



Salutations,

Didier 
Software Developer 😉

**Comment by openhautomation** [comment]
Bonjour Didier, merci pour ton aide.

Sans les états affichés c'est compliqué.

Pour ce qui est de ton second screen shot, C'est un problème que je rencontre également avec d'autre plugin, je vais essayer de regarder.

Si tu souhaites un template pour le Paro, tu me listes les commandes que tu veux avec un ordre pour l'affichage et je l'intègre dans le plugin.

**Comment by boxsters1423** [comment]
![FF21164C-4E38-40CE-A44E-0604DBDDA842](https://user-images.githubusercontent.com/33317024/68533423-0a535f80-0329-11ea-83bc-ce73fd19a3c9.jpeg)

**Comment by boxsters1423** [comment]
![B2B76886-7129-4DE2-949C-6BD63537C03C](https://user-images.githubusercontent.com/33317024/68533440-44bcfc80-0329-11ea-82ad-20ff72a86501.jpeg)

**Comment by openhautomation** [comment]
J'ai fait des modifications, je pense que la prochaine version corrigera ce problème.
Merci pour ton aide

**Comment by boxsters1423** [comment]
Superbe ça fonctionne ! 😁👍
![578875C4-22A8-46BE-BC7D-F8D8A329509B](https://user-images.githubusercontent.com/33317024/68567218-c0699700-0458-11ea-88dc-c121014f1cb9.png)
Il y a moyen de te verser de quoi aller boire un café ☕️ pour te remercier ?
